name: Test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    strategy:
      matrix:
        environments: [dev, test, prod]
    steps:
      - name: check
        shell: pwsh
        run: |
          Write-Host "Deploy to env $env:TARGET_ENV"
        env:
          TARGET_ENV: ${{ matrix.environments }}
