name: Test

on:
  workflow_dispatch:
   inputs:
     cleanTables:
        default: true
        type: boolean
        required: false
     fillTables:
        default: true
        type: boolean
        required: false
    

jobs:
  deploy:
    runs-on: windows-latest
    strategy:
      matrix:
        environments: [dev, test, prod]
    steps:
      - name: check
        if: inputs.cleanTables == true && inputs.fillTables == true
        shell: pwsh
        run: |
          Write-Host "Deploy to env $env:TARGET_ENV"
        env:
          TARGET_ENV: ${{ matrix.environments }}
      - name: testing
        shell: powershell
        run: |
          ./power.ps1
      - name: fetch vars
        shell: powershell
        run: Write-Host "Session $env:RemoteInstanceId"
        
